Repository nyu-devops-fall19-wishlists/wishlists, pull requests merged in 2019-10, with the labels that each got.

#39 Added minimal requirements.txt and Vagrantfile
  Vagrantfile
  requirements.txt
Labels: technical debt

#41 Ignoring OS specific and database specific files in gitignore
  .gitignore
Labels: technical debt

#45 Update flask
  Vagrantfile
  service/__init__.py
  service/app.py
  templates/base.html
Labels: enhancement

#44 Added the Wishlists DB
  Vagrantfile
Labels: technical debt

#48 Delete app.py
  app.py
Labels: technical debt

#58 Another pre-commit to check Pylint score
  .pylintrc
  Vagrantfile
  pre-commit
  requirements.txt
Labels: technical debt

#56 Update README.md
  README.md
Labels: documentation

#57 Updated DB Schema to include customer id. Also renamed one field
  service/models.py
  tests/test_wishlist.py
  tests/test_wishlist_products.py
Labels: enhancement

#59 Model names following PEP8 convention
  service/models.py
  service/service.py
  tests/test_wishlist_product.py
Labels: technical debt

#60 Fix: Remove customer_id from primary keys
  service/models.py
Labels: enhancement

#61 Implement Create Wishlist API
  service/models.py
  service/service.py
  tests/test_service.py
  tests/test_wishlist.py
Labels: enhancement

#62 Adding readme instructions to execute the service.
  README.md
Labels: technical debt

#65 Improving pylint score
  .pylintrc
  service/__init__.py
  service/service.py
  tests/test_service.py
  tests/test_wishlist.py
  tests/test_wishlist_product.py
Labels: technical debt
